### ISSUE TITLE
I can’t find the ${lastest-version} ’s  value

### ISSUE THREAD

**Issue by monkeydone** [nekocode/ResourceInspector#2]
${lastest-version} is the lastest version.

but I can’t find the value,Can  you give me a suggest.

**Comment by nekocode** [comment]
Check the jitpack version number in the README's second line (It's 0.3 now). You need to replace the `${lastest-version}` to this number by yourslef.

**Comment by monkeydone** [comment]
I add the link to find the lastest version for be easing. and pull request.
